### ISSUE TITLE
Struktur halaman web + Order proses

### ISSUE THREAD

**Issue by adhikasp** [blibli-future/blusea#6]
# Blusea Website Page Structure

```
Public page
- home page             /
- About/Kontak          /about
- login customer        /my-user/login
- daftar customer       /my-user/register
- login catering        /my-catering/login
- daftar catering       /my-catering/register

Customer
- public profile        /user/{id}
- CMS (MUST LOGIN)
  - dashboard           /my-user/dashboard
  - order history       /my-user/order
  - order in status 0   /my-user/cart
  - checkout            /my-user/checkout
  - setting             /my-user/setting

Catering
- public profile        /catering/{username}
- CMS (MUST LOGIN)
  - dashboard           /my-catering/dashboard
  - order               /my-catering/order
  - setting             /my-catering/setting
  - product             /my-catering/product	
    - add               /my-catering/product/add
    - edit              /my-catering/product/{idProduct}/edit
    - remove            /my-catering/product/{idProduct}/delete
```

# Catatan

- Semua halaman yang bersifat publik (profil publik customer dan catering)
  di handle oleh PublicController.
- Halaman yang berhubungan dengan order di handle oleh CustomerController atau 
  CateringController, tergantung itu perlu diurus siapa.

# Order Process Lifecyle

Order memiliki beberapa status yang mungkin dimilikinya pada suatu waktu:

- 0 = customer still shopping
- 1 = customer checkout and pay dp, waiting for confirmation from catering
- 2 = catering say OK and starting to prepare order
- 3 = order shipped and completed (masuk ke order history)

Awalnya customer yang baru daftar akan otomatis punya objek Order dengan status 0. 
Dia dapat menambahkan produk ke Ordernya (masih dalam status CART). Jika dia melakukan
proses checkout, maka status Ordernya akan menjadi 1. Pada saat ini otomatis sistem 
akan membuat objek Order baru dengan status 0 untuk si customer tersebut (hal ini agar
customer selalu dapat shopping). Untuk order yang sudah di checkout dan dibayar DP nya,
customer sudah lepas tangan dan hanya dapat melihat status progress pemesanan yang di handle
oleh pihak catering.

Catering akan menerima suat Order ketika seorang consumer selesai checkout. Dia dapat menerima pesanan
itu (say OKE) atau menolak. Menolak -> Order di hapus. Menerima -> status order naik menjadi 2 (WAITING status). Jika sudah hari H dan catering telah mengirim pesanan, maka dia dapat menekan tombol selesai
(FINISH status).

# TODO

- [ ]  Ubah URL jadi sesuai di atas
- [ ]  Buat halaman-halaman yang belum ada
- [ ]  Percantik halaman-halaman sebelumnya
- [ ]  Bikin halaman proses Order (sistem backend sudah jadi 6becefb189)

Mention @awidardi
